version: '3' # Docker Compose file version
services: # docker build, docker run, port, gan volumes
 build_html:
   container_name: cons-html
   build: . # docker build .
   volumes:
     - .:/usr/share/nginx/html
   #image:
   ports:
     - 3001:80

# docker-compose up -d
# docker-compose down
# docker-compose build --> docker-compose up -d