name: Deploy
on:
push:
    branches:
        - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USER }}
            key: ${{ secrets.VPS_KEY }}
            script: |
                cd /root/html-demo-ci-cd
                git pull